// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExistMessage.proto

package com.stupidbeauty.exist;

public final class ExistMessageContainer {
  private ExistMessageContainer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServicePublishMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.exist.ServicePublishMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 port = 2;</code>
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 2;</code>
     */
    int getPort();

    /**
     * <code>required .com.stupidbeauty.exist.ServicePublishMessage.ServiceProtocolType protocolType = 3;</code>
     */
    boolean hasProtocolType();
    /**
     * <code>required .com.stupidbeauty.exist.ServicePublishMessage.ServiceProtocolType protocolType = 3;</code>
     */
    com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.ServiceProtocolType getProtocolType();
  }
  /**
   * Protobuf type {@code com.stupidbeauty.exist.ServicePublishMessage}
   */
  public static final class ServicePublishMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.exist.ServicePublishMessage)
      ServicePublishMessageOrBuilder {
    // Use ServicePublishMessage.newBuilder() to construct.
    private ServicePublishMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServicePublishMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServicePublishMessage defaultInstance;
    public static ServicePublishMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ServicePublishMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServicePublishMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              port_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.ServiceProtocolType value = com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.ServiceProtocolType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                protocolType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ServicePublishMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ServicePublishMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.class, com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ServicePublishMessage> PARSER =
        new com.google.protobuf.AbstractParser<ServicePublishMessage>() {
      public ServicePublishMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServicePublishMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServicePublishMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.stupidbeauty.exist.ServicePublishMessage.ServiceProtocolType}
     */
    public enum ServiceProtocolType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HTTP = 0;</code>
       */
      HTTP(0, 0),
      /**
       * <code>UDP = 1;</code>
       */
      UDP(1, 1),
      /**
       * <code>MQTT = 2;</code>
       */
      MQTT(2, 2),
      /**
       * <code>TCP = 3;</code>
       */
      TCP(3, 3),
      ;

      /**
       * <code>HTTP = 0;</code>
       */
      public static final int HTTP_VALUE = 0;
      /**
       * <code>UDP = 1;</code>
       */
      public static final int UDP_VALUE = 1;
      /**
       * <code>MQTT = 2;</code>
       */
      public static final int MQTT_VALUE = 2;
      /**
       * <code>TCP = 3;</code>
       */
      public static final int TCP_VALUE = 3;


      public final int getNumber() { return value; }

      public static ServiceProtocolType valueOf(int value) {
        switch (value) {
          case 0: return HTTP;
          case 1: return UDP;
          case 2: return MQTT;
          case 3: return TCP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ServiceProtocolType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ServiceProtocolType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ServiceProtocolType>() {
              public ServiceProtocolType findValueByNumber(int number) {
                return ServiceProtocolType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final ServiceProtocolType[] VALUES = values();

      public static ServiceProtocolType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ServiceProtocolType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.stupidbeauty.exist.ServicePublishMessage.ServiceProtocolType)
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>required int32 port = 2;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int PROTOCOLTYPE_FIELD_NUMBER = 3;
    private com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.ServiceProtocolType protocolType_;
    /**
     * <code>required .com.stupidbeauty.exist.ServicePublishMessage.ServiceProtocolType protocolType = 3;</code>
     */
    public boolean hasProtocolType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .com.stupidbeauty.exist.ServicePublishMessage.ServiceProtocolType protocolType = 3;</code>
     */
    public com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.ServiceProtocolType getProtocolType() {
      return protocolType_;
    }

    private void initFields() {
      name_ = "";
      port_ = 0;
      protocolType_ = com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.ServiceProtocolType.HTTP;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProtocolType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, protocolType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, protocolType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.exist.ServicePublishMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.exist.ServicePublishMessage)
        com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ServicePublishMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ServicePublishMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.class, com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.Builder.class);
      }

      // Construct using com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        protocolType_ = com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.ServiceProtocolType.HTTP;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ServicePublishMessage_descriptor;
      }

      public com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage getDefaultInstanceForType() {
        return com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.getDefaultInstance();
      }

      public com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage build() {
        com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage buildPartial() {
        com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage result = new com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.protocolType_ = protocolType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage) {
          return mergeFrom((com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage other) {
        if (other == com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasProtocolType()) {
          setProtocolType(other.getProtocolType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        if (!hasProtocolType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>required int32 port = 2;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 2;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000002;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 2;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }

      private com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.ServiceProtocolType protocolType_ = com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.ServiceProtocolType.HTTP;
      /**
       * <code>required .com.stupidbeauty.exist.ServicePublishMessage.ServiceProtocolType protocolType = 3;</code>
       */
      public boolean hasProtocolType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .com.stupidbeauty.exist.ServicePublishMessage.ServiceProtocolType protocolType = 3;</code>
       */
      public com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.ServiceProtocolType getProtocolType() {
        return protocolType_;
      }
      /**
       * <code>required .com.stupidbeauty.exist.ServicePublishMessage.ServiceProtocolType protocolType = 3;</code>
       */
      public Builder setProtocolType(com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.ServiceProtocolType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        protocolType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.stupidbeauty.exist.ServicePublishMessage.ServiceProtocolType protocolType = 3;</code>
       */
      public Builder clearProtocolType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        protocolType_ = com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.ServiceProtocolType.HTTP;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.exist.ServicePublishMessage)
    }

    static {
      defaultInstance = new ServicePublishMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.exist.ServicePublishMessage)
  }

  public interface ServiceProbeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.exist.ServiceProbeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 port = 1;</code>
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 1;</code>
     */
    int getPort();
  }
  /**
   * Protobuf type {@code com.stupidbeauty.exist.ServiceProbeMessage}
   */
  public static final class ServiceProbeMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.exist.ServiceProbeMessage)
      ServiceProbeMessageOrBuilder {
    // Use ServiceProbeMessage.newBuilder() to construct.
    private ServiceProbeMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServiceProbeMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServiceProbeMessage defaultInstance;
    public static ServiceProbeMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ServiceProbeMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceProbeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              port_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ServiceProbeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ServiceProbeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.class, com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ServiceProbeMessage> PARSER =
        new com.google.protobuf.AbstractParser<ServiceProbeMessage>() {
      public ServiceProbeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceProbeMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceProbeMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PORT_FIELD_NUMBER = 1;
    private int port_;
    /**
     * <code>required int32 port = 1;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 port = 1;</code>
     */
    public int getPort() {
      return port_;
    }

    private void initFields() {
      port_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, port_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, port_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.exist.ServiceProbeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.exist.ServiceProbeMessage)
        com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ServiceProbeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ServiceProbeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.class, com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.Builder.class);
      }

      // Construct using com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ServiceProbeMessage_descriptor;
      }

      public com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage getDefaultInstanceForType() {
        return com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.getDefaultInstance();
      }

      public com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage build() {
        com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage buildPartial() {
        com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage result = new com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage) {
          return mergeFrom((com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage other) {
        if (other == com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.getDefaultInstance()) return this;
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPort()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int port_ ;
      /**
       * <code>required int32 port = 1;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 port = 1;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 1;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000001;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 1;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.exist.ServiceProbeMessage)
    }

    static {
      defaultInstance = new ServiceProbeMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.exist.ServiceProbeMessage)
  }

  public interface ExistMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.exist.ExistMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.stupidbeauty.exist.ExistMessage.MessageType messageType = 1;</code>
     */
    boolean hasMessageType();
    /**
     * <code>required .com.stupidbeauty.exist.ExistMessage.MessageType messageType = 1;</code>
     */
    com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.MessageType getMessageType();

    /**
     * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
     */
    boolean hasServicePublishMessage();
    /**
     * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
     */
    com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage getServicePublishMessage();
    /**
     * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
     */
    com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessageOrBuilder getServicePublishMessageOrBuilder();

    /**
     * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
     */
    boolean hasServiceProbeMessage();
    /**
     * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
     */
    com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage getServiceProbeMessage();
    /**
     * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
     */
    com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessageOrBuilder getServiceProbeMessageOrBuilder();
  }
  /**
   * Protobuf type {@code com.stupidbeauty.exist.ExistMessage}
   */
  public static final class ExistMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.exist.ExistMessage)
      ExistMessageOrBuilder {
    // Use ExistMessage.newBuilder() to construct.
    private ExistMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExistMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExistMessage defaultInstance;
    public static ExistMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ExistMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExistMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.MessageType value = com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                messageType_ = value;
              }
              break;
            }
            case 18: {
              com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = servicePublishMessage_.toBuilder();
              }
              servicePublishMessage_ = input.readMessage(com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(servicePublishMessage_);
                servicePublishMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = serviceProbeMessage_.toBuilder();
              }
              serviceProbeMessage_ = input.readMessage(com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(serviceProbeMessage_);
                serviceProbeMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ExistMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ExistMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.class, com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ExistMessage> PARSER =
        new com.google.protobuf.AbstractParser<ExistMessage>() {
      public ExistMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExistMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExistMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.stupidbeauty.exist.ExistMessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SERVICEPUBLISH = 0;</code>
       */
      SERVICEPUBLISH(0, 0),
      /**
       * <code>SERVICEPROBE = 1;</code>
       */
      SERVICEPROBE(1, 1),
      ;

      /**
       * <code>SERVICEPUBLISH = 0;</code>
       */
      public static final int SERVICEPUBLISH_VALUE = 0;
      /**
       * <code>SERVICEPROBE = 1;</code>
       */
      public static final int SERVICEPROBE_VALUE = 1;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return SERVICEPUBLISH;
          case 1: return SERVICEPROBE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.stupidbeauty.exist.ExistMessage.MessageType)
    }

    private int bitField0_;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.MessageType messageType_;
    /**
     * <code>required .com.stupidbeauty.exist.ExistMessage.MessageType messageType = 1;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.stupidbeauty.exist.ExistMessage.MessageType messageType = 1;</code>
     */
    public com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.MessageType getMessageType() {
      return messageType_;
    }

    public static final int SERVICEPUBLISHMESSAGE_FIELD_NUMBER = 2;
    private com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage servicePublishMessage_;
    /**
     * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
     */
    public boolean hasServicePublishMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
     */
    public com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage getServicePublishMessage() {
      return servicePublishMessage_;
    }
    /**
     * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
     */
    public com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessageOrBuilder getServicePublishMessageOrBuilder() {
      return servicePublishMessage_;
    }

    public static final int SERVICEPROBEMESSAGE_FIELD_NUMBER = 3;
    private com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage serviceProbeMessage_;
    /**
     * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
     */
    public boolean hasServiceProbeMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
     */
    public com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage getServiceProbeMessage() {
      return serviceProbeMessage_;
    }
    /**
     * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
     */
    public com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessageOrBuilder getServiceProbeMessageOrBuilder() {
      return serviceProbeMessage_;
    }

    private void initFields() {
      messageType_ = com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.MessageType.SERVICEPUBLISH;
      servicePublishMessage_ = com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.getDefaultInstance();
      serviceProbeMessage_ = com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasServicePublishMessage()) {
        if (!getServicePublishMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasServiceProbeMessage()) {
        if (!getServiceProbeMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, servicePublishMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, serviceProbeMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, servicePublishMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, serviceProbeMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.stupidbeauty.exist.ExistMessageContainer.ExistMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ExistMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ExistMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ExistMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ExistMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ExistMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ExistMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ExistMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ExistMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stupidbeauty.exist.ExistMessageContainer.ExistMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.stupidbeauty.exist.ExistMessageContainer.ExistMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.exist.ExistMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.exist.ExistMessage)
        com.stupidbeauty.exist.ExistMessageContainer.ExistMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ExistMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ExistMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.class, com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.Builder.class);
      }

      // Construct using com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getServicePublishMessageFieldBuilder();
          getServiceProbeMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageType_ = com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.MessageType.SERVICEPUBLISH;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (servicePublishMessageBuilder_ == null) {
          servicePublishMessage_ = com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.getDefaultInstance();
        } else {
          servicePublishMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (serviceProbeMessageBuilder_ == null) {
          serviceProbeMessage_ = com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.getDefaultInstance();
        } else {
          serviceProbeMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.exist.ExistMessageContainer.internal_static_com_stupidbeauty_exist_ExistMessage_descriptor;
      }

      public com.stupidbeauty.exist.ExistMessageContainer.ExistMessage getDefaultInstanceForType() {
        return com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.getDefaultInstance();
      }

      public com.stupidbeauty.exist.ExistMessageContainer.ExistMessage build() {
        com.stupidbeauty.exist.ExistMessageContainer.ExistMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stupidbeauty.exist.ExistMessageContainer.ExistMessage buildPartial() {
        com.stupidbeauty.exist.ExistMessageContainer.ExistMessage result = new com.stupidbeauty.exist.ExistMessageContainer.ExistMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (servicePublishMessageBuilder_ == null) {
          result.servicePublishMessage_ = servicePublishMessage_;
        } else {
          result.servicePublishMessage_ = servicePublishMessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (serviceProbeMessageBuilder_ == null) {
          result.serviceProbeMessage_ = serviceProbeMessage_;
        } else {
          result.serviceProbeMessage_ = serviceProbeMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.exist.ExistMessageContainer.ExistMessage) {
          return mergeFrom((com.stupidbeauty.exist.ExistMessageContainer.ExistMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.exist.ExistMessageContainer.ExistMessage other) {
        if (other == com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasServicePublishMessage()) {
          mergeServicePublishMessage(other.getServicePublishMessage());
        }
        if (other.hasServiceProbeMessage()) {
          mergeServiceProbeMessage(other.getServiceProbeMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageType()) {
          
          return false;
        }
        if (hasServicePublishMessage()) {
          if (!getServicePublishMessage().isInitialized()) {
            
            return false;
          }
        }
        if (hasServiceProbeMessage()) {
          if (!getServiceProbeMessage().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.exist.ExistMessageContainer.ExistMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.exist.ExistMessageContainer.ExistMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.MessageType messageType_ = com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.MessageType.SERVICEPUBLISH;
      /**
       * <code>required .com.stupidbeauty.exist.ExistMessage.MessageType messageType = 1;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.stupidbeauty.exist.ExistMessage.MessageType messageType = 1;</code>
       */
      public com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.MessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>required .com.stupidbeauty.exist.ExistMessage.MessageType messageType = 1;</code>
       */
      public Builder setMessageType(com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.stupidbeauty.exist.ExistMessage.MessageType messageType = 1;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = com.stupidbeauty.exist.ExistMessageContainer.ExistMessage.MessageType.SERVICEPUBLISH;
        onChanged();
        return this;
      }

      private com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage servicePublishMessage_ = com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage, com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.Builder, com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessageOrBuilder> servicePublishMessageBuilder_;
      /**
       * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
       */
      public boolean hasServicePublishMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
       */
      public com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage getServicePublishMessage() {
        if (servicePublishMessageBuilder_ == null) {
          return servicePublishMessage_;
        } else {
          return servicePublishMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
       */
      public Builder setServicePublishMessage(com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage value) {
        if (servicePublishMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          servicePublishMessage_ = value;
          onChanged();
        } else {
          servicePublishMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
       */
      public Builder setServicePublishMessage(
          com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.Builder builderForValue) {
        if (servicePublishMessageBuilder_ == null) {
          servicePublishMessage_ = builderForValue.build();
          onChanged();
        } else {
          servicePublishMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
       */
      public Builder mergeServicePublishMessage(com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage value) {
        if (servicePublishMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              servicePublishMessage_ != com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.getDefaultInstance()) {
            servicePublishMessage_ =
              com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.newBuilder(servicePublishMessage_).mergeFrom(value).buildPartial();
          } else {
            servicePublishMessage_ = value;
          }
          onChanged();
        } else {
          servicePublishMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
       */
      public Builder clearServicePublishMessage() {
        if (servicePublishMessageBuilder_ == null) {
          servicePublishMessage_ = com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.getDefaultInstance();
          onChanged();
        } else {
          servicePublishMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
       */
      public com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.Builder getServicePublishMessageBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getServicePublishMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
       */
      public com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessageOrBuilder getServicePublishMessageOrBuilder() {
        if (servicePublishMessageBuilder_ != null) {
          return servicePublishMessageBuilder_.getMessageOrBuilder();
        } else {
          return servicePublishMessage_;
        }
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage, com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.Builder, com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessageOrBuilder> 
          getServicePublishMessageFieldBuilder() {
        if (servicePublishMessageBuilder_ == null) {
          servicePublishMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage, com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessage.Builder, com.stupidbeauty.exist.ExistMessageContainer.ServicePublishMessageOrBuilder>(
                  getServicePublishMessage(),
                  getParentForChildren(),
                  isClean());
          servicePublishMessage_ = null;
        }
        return servicePublishMessageBuilder_;
      }

      private com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage serviceProbeMessage_ = com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage, com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.Builder, com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessageOrBuilder> serviceProbeMessageBuilder_;
      /**
       * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
       */
      public boolean hasServiceProbeMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
       */
      public com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage getServiceProbeMessage() {
        if (serviceProbeMessageBuilder_ == null) {
          return serviceProbeMessage_;
        } else {
          return serviceProbeMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
       */
      public Builder setServiceProbeMessage(com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage value) {
        if (serviceProbeMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serviceProbeMessage_ = value;
          onChanged();
        } else {
          serviceProbeMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
       */
      public Builder setServiceProbeMessage(
          com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.Builder builderForValue) {
        if (serviceProbeMessageBuilder_ == null) {
          serviceProbeMessage_ = builderForValue.build();
          onChanged();
        } else {
          serviceProbeMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
       */
      public Builder mergeServiceProbeMessage(com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage value) {
        if (serviceProbeMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              serviceProbeMessage_ != com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.getDefaultInstance()) {
            serviceProbeMessage_ =
              com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.newBuilder(serviceProbeMessage_).mergeFrom(value).buildPartial();
          } else {
            serviceProbeMessage_ = value;
          }
          onChanged();
        } else {
          serviceProbeMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
       */
      public Builder clearServiceProbeMessage() {
        if (serviceProbeMessageBuilder_ == null) {
          serviceProbeMessage_ = com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.getDefaultInstance();
          onChanged();
        } else {
          serviceProbeMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
       */
      public com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.Builder getServiceProbeMessageBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getServiceProbeMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
       */
      public com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessageOrBuilder getServiceProbeMessageOrBuilder() {
        if (serviceProbeMessageBuilder_ != null) {
          return serviceProbeMessageBuilder_.getMessageOrBuilder();
        } else {
          return serviceProbeMessage_;
        }
      }
      /**
       * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage, com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.Builder, com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessageOrBuilder> 
          getServiceProbeMessageFieldBuilder() {
        if (serviceProbeMessageBuilder_ == null) {
          serviceProbeMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage, com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage.Builder, com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessageOrBuilder>(
                  getServiceProbeMessage(),
                  getParentForChildren(),
                  isClean());
          serviceProbeMessage_ = null;
        }
        return serviceProbeMessageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.exist.ExistMessage)
    }

    static {
      defaultInstance = new ExistMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.exist.ExistMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_exist_ServicePublishMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_stupidbeauty_exist_ServicePublishMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_exist_ServiceProbeMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_stupidbeauty_exist_ServiceProbeMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_exist_ExistMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_stupidbeauty_exist_ExistMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ExistMessage.proto\022\026com.stupidbeauty.e" +
      "xist\"\311\001\n\025ServicePublishMessage\022\014\n\004name\030\001" +
      " \002(\t\022\014\n\004port\030\002 \002(\005\022W\n\014protocolType\030\003 \002(\016" +
      "2A.com.stupidbeauty.exist.ServicePublish" +
      "Message.ServiceProtocolType\";\n\023ServicePr" +
      "otocolType\022\010\n\004HTTP\020\000\022\007\n\003UDP\020\001\022\010\n\004MQTT\020\002\022" +
      "\007\n\003TCP\020\003\"#\n\023ServiceProbeMessage\022\014\n\004port\030" +
      "\001 \002(\005\"\242\002\n\014ExistMessage\022E\n\013messageType\030\001 " +
      "\002(\01620.com.stupidbeauty.exist.ExistMessag" +
      "e.MessageType\022L\n\025servicePublishMessage\030\002",
      " \001(\0132-.com.stupidbeauty.exist.ServicePub" +
      "lishMessage\022H\n\023serviceProbeMessage\030\003 \001(\013" +
      "2+.com.stupidbeauty.exist.ServiceProbeMe" +
      "ssage\"3\n\013MessageType\022\022\n\016SERVICEPUBLISH\020\000" +
      "\022\020\n\014SERVICEPROBE\020\001B/\n\026com.stupidbeauty.e" +
      "xistB\025ExistMessageContainer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_stupidbeauty_exist_ServicePublishMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_exist_ServicePublishMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_stupidbeauty_exist_ServicePublishMessage_descriptor,
        new java.lang.String[] { "Name", "Port", "ProtocolType", });
    internal_static_com_stupidbeauty_exist_ServiceProbeMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_stupidbeauty_exist_ServiceProbeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_stupidbeauty_exist_ServiceProbeMessage_descriptor,
        new java.lang.String[] { "Port", });
    internal_static_com_stupidbeauty_exist_ExistMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_stupidbeauty_exist_ExistMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_stupidbeauty_exist_ExistMessage_descriptor,
        new java.lang.String[] { "MessageType", "ServicePublishMessage", "ServiceProbeMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
