// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.stupidbeauty.exist;

  /**
   * Protobuf type {@code com.stupidbeauty.exist.ExistMessage}
   */
  public final class ExistMessage 
  {
    public ExistMessage() 
    { 
      this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); 
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;

    private int bitField0_;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_; //!< Message type.

    public ExistMessage setMessageType(int messageType)
    {
      messageType_=messageType;
      return this;
    }
    
    public static class MessageType
    {
      public static final Integer SERVICEPUBLISH=0; //!< Service publish.
    }
    
    /**
     * <code>required .com.stupidbeauty.exist.ExistMessage.MessageType messageType = 1;</code>
     */
    public int getMessageType() 
    {
      return messageType_;
    }

    public static final int SERVICEPUBLISHMESSAGE_FIELD_NUMBER = 2;
    private byte[] servicePublishMessage_;
    
    public ExistMessage setServicePublishMessage(byte[] servicePublishMessage)
    {
      servicePublishMessage_=servicePublishMessage;
      return this;
    }

    /**
     * <code>optional .com.stupidbeauty.exist.ServicePublishMessage servicePublishMessage = 2;</code>
     */
    public byte[] getServicePublishMessage() 
    {
      return servicePublishMessage_;
    }

    private com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage serviceProbeMessage_;

    /**
     * <code>optional .com.stupidbeauty.exist.ServiceProbeMessage serviceProbeMessage = 3;</code>
     */
    public com.stupidbeauty.exist.ExistMessageContainer.ServiceProbeMessage getServiceProbeMessage() {
      return serviceProbeMessage_;
    }

    private byte memoizedIsInitialized = -1;

    private int memoizedSerializedSize = -1;
  }
